version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.0.0
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.3.0

defaults: &defaults
  working_directory: ~/repo


jobs:
  test:
    <<: *defaults

    docker:
      - image: cimg/node:18.15.0-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
            - v1-deps-

      - run: yarn install

      - run:
          name: Lint
          command: yarn worker lint

      - run:
          name: Run tests
          command: yarn worker test

      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

  publish:
    <<: *defaults

    parameters:
      app:
        description: The app to build and publish
        default: "worker"
        type: string

    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true

    steps:
      - checkout
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: "set $DOCKER_TAG"
          command:
            | # set $DOCKER_TAG as either the git tag that triggered the build, or the git sha (for deploy-test branch)
            if [ "<<pipeline.git.tag>>" == "" ]; then echo 'export DOCKER_TAG="<<pipeline.git.revision>>"' >> $BASH_ENV; else echo 'export DOCKER_TAG="<<pipeline.git.tag>>"' >> $BASH_ENV; fi

      - when:
          condition:
            equal: [worker, <<parameters.app>>]
          steps:
            - run:
                name: Publish docker image - worker
                command: |
                  eval $(aws ecr get-login --no-include-email --region eu-west-2)
                  docker build --build-arg DOCKER_TAG=$DOCKER_TAG -t 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/forms-worker:$DOCKER_TAG -f ./worker/Dockerfile .
                  docker push 523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/forms-worker:$DOCKER_TAG


  deploy:
    <<: *defaults

    parameters:
      namespace:
        type: string

    machine:
      image: ubuntu-2004:202201-02

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install the eksctl tool
          command: |
            if which eksctl > /dev/null; then
              echo "eksctl is already installed"
              exit 0
            fi

            mkdir -p eksctl_download
            curl --silent --location --retry 5 "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" \
              | tar xz -C eksctl_download
            chmod +x eksctl_download/eksctl
            SUDO=""
            if [ $(id -u) -ne 0 ] && which sudo > /dev/null ; then
              SUDO="sudo"
            fi
            $SUDO mv eksctl_download/eksctl /usr/local/bin/
            rmdir eksctl_download

      - run:
          name: Install OpenVPN
          command: |
            sudo apt-get update
            sudo apt-get install net-tools -y
            sudo apt-get install openvpn openvpn-systemd-resolved -y

      - run:
          name: Check IP before VPN connection
          command: |
            ip a
            echo "Public IP before VPN connection is $(curl checkip.amazonaws.com)"

      - run:
          name: VPN Setup
          background: true
          command: |
            echo $VPN_CLIENT_CONFIG | base64 --decode > /tmp/config.ovpn

            if grep -q auth-user-pass /tmp/config.ovpn; then
              if [ -z "${VPN_USER:-}" ] || [ -z "${VPN_PASSWORD:-}" ]; then
                echo "Your VPN client is configured with a user-locked profile. Make sure to set the VPN_USER and VPN_PASSWORD environment variables"
                exit 1
              else
                printf "$VPN_USER\\n$VPN_PASSWORD" > /tmp/vpn.login
              fi
            fi

            SYS_RES_DNS=$(systemd-resolve --status | grep 'DNS Servers'|awk '{print $3}')
            echo $SYS_RES_DNS

            phone_home=$(ss -Hnto state established '( sport = :ssh )' | head -n1 | awk '{ split($4, a, ":"); print a[1] }') || $(sudo netstat -an | grep ':22 .*ESTABLISHED' | head -n1 | awk '{ split($5, a, ":"); print a[1] }')
            echo $phone_home

            vpn_command=(sudo openvpn
              --config /tmp/config.ovpn
              --route $SYS_RES_DNS 255.255.255.255 net_gateway
              --route 169.254.0.0 255.255.0.0 net_gateway
              --script-security 2
              --up /etc/openvpn/update-systemd-resolved --up-restart
              --down /etc/openvpn/update-systemd-resolved --down-pre
              --dhcp-option DOMAIN-ROUTE .)

            if grep -q auth-user-pass /tmp/config.ovpn; then
              vpn_command+=(--auth-user-pass /tmp/vpn.login)
            fi

            if [ -n "$phone_home" ]; then
              vpn_command+=(--route $phone_home 255.255.255.255 net_gateway)
            fi

            for IP in $(host runner.circleci.com | awk '{ print $4; }')
              do
                vpn_command+=(--route $IP 255.255.255.255 net_gateway)
                echo $IP
            done

            "${vpn_command[@]}" > /tmp/openvpn.log

      - run:
          name: Wait for the connection to be established and check IP
          command: |
            until [ -f /tmp/openvpn.log ] && [ "$(grep -c "Initialization Sequence Completed" /tmp/openvpn.log)" != 0 ]; do
              echo "Attempting to connect to VPN server..."
              sleep 3;
            done

            printf "\nVPN connected\n"
            printf "\nPublic IP is now $(curl checkip.amazonaws.com)\n"

      - run:
          name: "set $DOCKER_TAG"
          command:
            | # set $DOCKER_TAG as either the git tag that triggered the build, or the git sha (for deploy-test branch)
            if [ "<<pipeline.git.tag>>" == "" ]; then echo 'export DOCKER_TAG="<<pipeline.git.revision>>"' >> $BASH_ENV; else echo 'export DOCKER_TAG="<<pipeline.git.tag>>"' >> $BASH_ENV; fi

      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: fco-forms-test
          aws-region: eu-west-2
          install-kubectl: true

      - kubernetes/update-container-image:
          namespace: << parameters.namespace >>
          container-image-updates: forms-worker=523508197323.dkr.ecr.eu-west-2.amazonaws.com/fco/forms-worker:$DOCKER_TAG
          resource-name: deployment/forms-worker

      - run:
          name: Disconnect from OpenVPN
          command: |
            sudo killall openvpn || true
          when: always

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - publish:
          name: publish-worker
          app: worker
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              only:
                - deploy-test
                - main
          context:
            - VPN
            - AWS

      - deploy:
          name: deploy-test
          namespace: fco-forms-test
          context:
            - VPN
            - AWS
          requires:
            - publish-worker
          filters:
            branches:
              only:
                - deploy-test