name: Docker build

on:
  workflow_call:
    inputs:
      push:
        description: Whether or not to push to ghcr
        default: false
        required: false
        type: boolean
      version:
        description: The version to tag the build with
        required: false
        type: string

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release details
        run: |
          echo "tag: ${{inputs.version}}, push: ${{inputs.push}}"

      - name: Build only
        if: ${{inputs.push == false}}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/Dockerfile
          push: false

      - name: Build and push
        if: ${{inputs.push == true}}
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/Dockerfile
          push: true
          tags: |
            ghcr.io/xgovformbuilder/forms-worker:${{ inputs.version }}
            ghcr.io/xgovformbuilder/forms-worker:latest