name: publish image


on:
  workflow_call:
    inputs:
      version:
        description: The version to tag the build with
        required: true
        type: string
jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: release details
        run: |
          echo "tag: ${{inputs.version}}"
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: worker/Dockerfile
          push: false
          tags: xgovformbuilder/digital-form-builder-worker
