name: Test

on:
  workflow_call:
    inputs:
      version:
        description: The version to tag the build with
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: install deps
        run: yarn install
      - name: test
        run: yarn worker test